# Generated by Django 2.2 on 2021-08-23 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotable_quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_created', to='quotable_quotes_app.User'),
        ),
    ]
