# Generated by Django 2.2 on 2021-08-23 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotable_quotes_app', '0002_auto_20210822_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='users_that_favorited',
        ),
    ]
