# Generated by Django 2.2 on 2021-08-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shows',
        ),
    ]
