# Generated by Django 2.2 on 2021-08-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0002_auto_20210821_2310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
