# Generated by Django 2.2 on 2021-08-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0002_auto_20210822_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='book',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
