# Generated by Django 2.2 on 2021-08-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0004_auto_20210822_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='users_that_favorited',
            field=models.ManyToManyField(related_name='books_favorited', to='favorite_books_app.User'),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
